# Generated by Django 3.1.4 on 2020-12-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('event_type', models.CharField(choices=[('offline event', 'offline event'), ('online event', 'online event')], default='offline', max_length=20)),
                ('start_date', models.DateField(help_text='YYYY-mm-dd', null=True)),
                ('end_date', models.DateField(help_text='YYYY-mm-dd', null=True)),
                ('start_time', models.TimeField(help_text='HH:MM', null=True)),
                ('end_time', models.TimeField(help_text='HH:MM', null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('coordinates_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coordinates_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('members_number', models.PositiveIntegerField(default=0)),
                ('host', models.CharField(max_length=30, null=True)),
                ('cover', models.ImageField(blank=True, default='./images/covers/fon.jpeg', null=True, upload_to='./images/covers/')),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.category')),
                ('join', models.ManyToManyField(blank=True, related_name='join', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'start_time', 'end_date', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(default='eee@gmail.com', max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='./images/profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinModelButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Join', 'Join'), ('UnJoin', 'UnJoin')], default='Join', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.events')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
