# Generated by Django 3.1.3 on 2020-11-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofileinfomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfomodel',
            name='portfolio',
        ),
    ]
