# Generated by Django 3.1.4 on 2020-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='coordinates_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='coordinates_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
