# Generated by Django 3.1.3 on 2020-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_userprofileinfomodel_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfomodel',
            name='password',
            field=models.CharField(default='qwqwqw12', max_length=30),
        ),
    ]
