# Generated by Django 3.1.4 on 2020-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201206_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='coordinates_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='coordinates_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
