# Generated by Django 3.1.4 on 2020-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201206_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='coordinates_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='coordinates_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
