# Generated by Django 3.1.3 on 2020-11-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20201125_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
    ]
